name: 'php-coverage-badge'
author: 'Michel Bobillier athos99@bluewin.ch'
description: 'PHP-Coverage-Badge is a gitaction for creating an SVG coverage badge from a PHP Clover XML file.'
branding: 
  icon: 'book-open'
  color: 'green'
inputs:
  report:
    description: 'The path to the report file.'
    required: false
    default: 'clover.xml'
  report_type:
    description: 'The type of the generated report. Currently supported: clover, cobertura.'
    required: false
    default: 'clover'
  coverage_line_badge_name:
    description: 'The name of the line coverage badge'
    required: false
    default: 'Line coverage'
  coverage_branche_badge_name:
    description: 'The name of the branch coverage badge'
    required: false
    default: 'Branche coverage'
  coverage_line_badge_path:
    description: 'The path of the line coverage badge'
    required: false
    default: 'coverage_line.svg'
  coverage_branche_badge_path:
    description: 'The path of the branch coverage badge'
    required: false
    default: 'coverage_breanche.svg'
  coverage_line_percent_ok:
    description: 'Acceptable limit of coverage line percent'
    required: false
    default: '80'
  coverage_branch_percent_ok:
    description: 'Acceptable limit of coverage barnch percent'
    required: false
    default: '60'
  push_badge:
    description: 'Defines whether the badges will be committed and pushed to the repository.'
    required: false
    default: 'false'
  commit_message:
    description: 'Commit message that will be used to commit.'
    required: false
    default: 'Update code coverages badges'
  commit_email:
    description: 'Email that will be used for the commit.'
    required: false
    default: 'actions@users.noreply.github.com'
  repo_token:
    description: 'Token to push the badge into the repository.'
    required: false
    default: 'NOT_SUPPLIED'
runs:
  using: "composite"
  steps:
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml
    - name: build badge
      shell: bash
      env:
        INPUT_REPORT: "${{ inputs.report }}"
        INPUT_REPORT_TYPE: "${{ inputs.report_type }}"
        INPUT_COVERAGE_LINE_BADGE_NAME: "${{ inputs.coverage_line_badge_name }}"
        INPUT_COVERAGE_BRANCHE_BADGE_NAME: "${{ inputs.coverage_branche_badge_name }}"
        INPUT_COVERAGE_LINE_BADGE_PATH: "${{ inputs.coverage_line_badge_path }}"
        INPUT_COVERAGE_BRANCHE_BADGE_PATH: "${{ inputs.coverage_branche_badge_path }}"
        INPUT_COVERAGE_LINE_PERCENT_OK: "${{    inputs.coverage_line_percent_ok }}"
        INPUT_COVERAGE_BRANCH_PERCENT_OK: "${{ inputs.coverage_branch_percent_ok }}"
        INPUT_PUSH_BADGE: "${{ inputs.push_badge }}"
        INPUT_REPO_TOKEN: "${{ inputs.repo_token }}"
        INPUT_COMMIT_MESSAGE: "${{ inputs.commit_message }}"
        INPUT_COMMIT_EMAIL: "${{ inputs.commit_email }}"       
      run: |
        php Build.php --report=$INPUT_REPORT \
          --report-type=$INPUT_REPORT_TYPE \
          --coverage-line-badge-name=$INPUT_COVERAGE_LINE_BADGE_NAME\
          --coverage-branche-badge-name=$INPUT_COVERAGE_BRANCHE_BADGE_NAME \
          --coverage-line-badge-path=$INPUT_COVERAGE_LINE_BADGE_PATH \
          --coverage-branche-badge-path=$INPUT_COVERAGE_BRANCHE_BADGE_PATH \
          --coverage-line-percent-ok=${INPUT_COVERAGE_LINE_PERCENT_OK} \
          --coverage-branch-percent-ok=${INPUT_COVERAGE_BRANCH_PERCENT_OK} \
          --push-badge=${INPUT_PUSH_BADGE} \
          --repo-token=${INPUT_REPO_TOKEN} \
          --commit-message=${INPUT_COMMIT_MESSAGE} \
          --commit-email=${INPUT_COMMIT_EMAIL}

