name: 'php-coverage-badge'
author: 'Michel Bobillier athos99@bluewin.ch'
description: 'PHP-Coverage-Badge is a gitaction for creating an SVG coverage badge from a PHP Clover or Corbertura XML file.'
branding: 
  icon: 'book-open'
  color: 'green'
inputs:
  report:
    description: 'The path to the report file.'
    required: false
    default: 'clover.xml'
  report_type:
    description: 'The type of the generated report. Currently supported: clover, cobertura.'
    required: false
    default: 'clover'
  coverage_line_badge_name:
    description: 'The name of the line coverage badge'
    required: false
    default: 'Line coverage'
  coverage_branch_badge_name:
    description: 'The name of the branch coverage badge'
    required: false
    default: 'Branch coverage'
  coverage_line_badge_path:
    description: 'The path of the line coverage badge'
    required: false
    default: 'coverage_line.svg'
  coverage_branch_badge_path:
    description: 'The path of the branch coverage badge'
    required: false
    default: 'coverage_breanche.svg'
  coverage_line_percent_ok:
    description: 'Acceptable limit of coverage line percent'
    required: false
    default: '80'
  coverage_branch_percent_ok:
    description: 'Acceptable limit of coverage barnch percent'
    required: false
    default: '60'
  push_badge:
    description: 'Defines whether the badges will be committed and pushed to the repository.'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml
    - name: build badge
      shell: bash
      env:
        INPUT_REPORT: "${{ inputs.report }}"
        INPUT_REPORT_TYPE: "${{ inputs.report_type }}"
        INPUT_COVERAGE_LINE_BADGE_NAME: "${{ inputs.coverage_line_badge_name }}"
        INPUT_COVERAGE_BRANCH_BADGE_NAME: "${{ inputs.coverage_branch_badge_name }}"
        INPUT_COVERAGE_LINE_BADGE_PATH: "${{ inputs.coverage_line_badge_path }}"
        INPUT_COVERAGE_BRANCH_BADGE_PATH: "${{ inputs.coverage_branch_badge_path }}"
        INPUT_COVERAGE_LINE_PERCENT_OK: "${{    inputs.coverage_line_percent_ok }}"
        INPUT_COVERAGE_BRANCH_PERCENT_OK: "${{ inputs.coverage_branch_percent_ok }}"
      run: |
        php Build.php --report="$INPUT_REPORT" \
          --report-type="$INPUT_REPORT_TYPE" \
          --coverage-line-badge-name="$INPUT_COVERAGE_LINE_BADGE_NAME"\
          --coverage-branch-badge-name="$INPUT_COVERAGE_BRANCH_BADGE_NAME" \
          --coverage-line-badge-path="$INPUT_COVERAGE_LINE_BADGE_PATH" \
          --coverage-branch-badge-path="$INPUT_COVERAGE_BRANCH_BADGE_PATH" \
          --coverage-line-percent-ok="${INPUT_COVERAGE_LINE_PERCENT_OK}" \
          --coverage-branch-percent-ok="${INPUT_COVERAGE_BRANCH_PERCENT_OK}" \

